apiVersion: slurm.ay.dev/v1
kind: SlurmDeployment
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: slurm
spec:
  chart:
    name: slurm
    repository: https://aaronyang0628.github.io/helm-chart-mirror/charts/slurm
    version: 1.0.6
    namespace: slurm
  values:
    mariadb:
      enabled: true
      port: 3306
      primary:
        persistence:
          enabled: false
          storageClass: ""
          size: 8Gi
    auth:
      ssh:
        configmap:
          name: slurm-ssh-auth-keys
          prefabPubKeys: ["ssh-rsa sample_public_key"]
    persistence:
      shared:
        enabled: true
        accessModes:
          - ReadWriteMany
        name: slurm-shared-storage
        storageClass: ""
        size: 8Gi
      mirror:
        registry: m.lab.zverse.space
    munged:
      image:
        registry: ghcr.io
        repository: aaronyang0628/slurm-munged
        tag: "intelmpi-250208-r0"
        pullPolicy: IfNotPresent
        pullSecrets: []
      extraVolumes: []
      extraVolumeMounts: []
    slurmdbd:
      image:
        registry: ghcr.io
        repository: aaronyang0628/slurm-slurmdbd
        tag: intelmpi-250208-r0
        pullPolicy: IfNotPresent
        pullSecrets: []
      extraVolumes: []
      extraVolumeMounts: []
    slurmctld:
      image:
        registry: ghcr.io
        repository: aaronyang0628/slurm-slurmctld
        tag: intelmpi-250208-r0
        pullPolicy: IfNotPresent
        pullSecrets: []
      extraVolumes: []
      extraVolumeMounts: []
    login:
      image:
        registry: ghcr.io
        repository: aaronyang0628/slurm-login
        tag: intelmpi-250208-r0-lensing-v4
        pullPolicy: IfNotPresent
        pullSecrets: []
      resources: 
        limits:
          cpu: 3000m
          ephemeral-storage: 50Gi
          memory: 8Gi
        requests:
          cpu: 500m
          ephemeral-storage: 8Gi
          memory: 1Gi
      extraVolumes: []
      extraVolumeMounts: []
    slurmdCPU:
      replicaCount: 1
      image:
        registry: ghcr.io
        repository: aaronyang0628/slurm-slurmd
        tag: openmpi-25.05
        pullPolicy: IfNotPresent
        pullSecrets: []
      resources: 
        requests:
          core: 1
          cpu: 500m
          ephemeral-storage: 10Gi
          memory: 1Gi
      extraVolumes: []
      extraVolumeMounts: []
    slurmdGPU:
      replicaCount: 1
      image:
        registry: ghcr.io
        repository: aaronyang0628/slurm-slurmd
        tag: intelmpi-250208-r0-lensing-v5.3
        pullPolicy: IfNotPresent
        pullSecrets: []
      resources: 
        requests:
          core: 1
          cpu: 500m
          ephemeral-storage: 10Gi
          memory: 1Gi
      extraVolumes: []
      extraVolumeMounts: []