apiVersion: slurm.ay.dev/v1
kind: SlurmDeployment
metadata:
  labels:
    app.kubernetes.io/name: operator
    app.kubernetes.io/managed-by: kustomize
  name: slurmdeployment
spec:
  chart:
    name: slurm
    repository: https://aaronyang0628.github.io/helm-chart-mirror/charts/slurm
    version: 1.0.4
    namespace: test
  values:
    mariadb:
      enabled: true
      port: 3306
      primary:
        persistence:
          enabled: false
          storageClass: ""
          size: 8Gi
    auth:
      ssh:
        configmap:
          name: slurm-ssh-auth-keys
          prefabPubKeys: ["ssh-rsa sample_public_key"]
    persistence:
      shared:
        enabled: true
        accessModes:
          - ReadWriteMany
        name: slurm-shared-storage
        storageClass: ""
        size: 8Gi
    image:
      mirror:
        registry: m.daocloud.io
    munged:
      image:
        registry: docker.io
        repository: aaron666/slurm-munged
        tag: latest
        pullPolicy: IfNotPresent
        pullSecrets: []
      extraVolumes: []
      extraVolumeMounts: []
    slurmdbd:
      image:
        registry: docker.io
        repository: aaron666/slurm-slurmdbd
        tag: latest
        pullPolicy: IfNotPresent
        pullSecrets: []
      extraVolumes: []
      extraVolumeMounts: []
    slurmctld:
      image:
        registry: docker.io
        repository: aaron666/slurm-slurmctld
        tag: latest
        pullPolicy: IfNotPresent
        pullSecrets: []
      extraVolumes: []
      extraVolumeMounts: []
    login:
      image:
        registry: docker.io
        repository: aaron666/slurm-login
        tag: intel-mpi
        pullPolicy: IfNotPresent
        pullSecrets: []
      resources: 
        limits:
          cpu: 3000m
          ephemeral-storage: 50Gi
          memory: 8Gi
        requests:
          cpu: 500m
          ephemeral-storage: 8Gi
          memory: 1Gi
      extraVolumes: []
      extraVolumeMounts: []
    slurmd:
      replicaCount: 1
      image:
        registry: docker.io
        repository: aaron666/slurm-slurmd
        tag: intel-mpi
        pullPolicy: IfNotPresent
        pullSecrets: []
      resources: 
        requests:
          core: 8
          cpu: 500m
          ephemeral-storage: 10Gi
          memory: 1Gi
      extraVolumes: []
      extraVolumeMounts: []

  
