apiVersion: v1
entries:
  argo-cd:
  - annotations:
      artifacthub.io/changes: |
        - kind: changed
          description: Bump argo-cd to v2.14.8
      artifacthub.io/signKey: |
        fingerprint: 2B8F22F57260EFA67BE1C5824B11F800CD9D2252
        url: https://argoproj.github.io/argo-helm/pgp_keys.asc
    apiVersion: v2
    appVersion: v2.14.8
    created: "2025-04-17T14:50:30.753998383+08:00"
    dependencies:
    - condition: redis-ha.enabled
      name: redis-ha
      repository: https://dandydeveloper.github.io/charts/
      version: 4.29.4
    description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery
      tool for Kubernetes.
    digest: d0f94b20bd2a458debc1e6c95ffa8b3094b523d2e002300864e78924a0b1ce84
    home: https://github.com/argoproj/argo-helm
    icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
    keywords:
    - argoproj
    - argocd
    - gitops
    kubeVersion: '>=1.25.0-0'
    maintainers:
    - name: argoproj
      url: https://argoproj.github.io/
    name: argo-cd
    sources:
    - https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
    - https://github.com/argoproj/argo-cd
    urls:
    - argo/argo-cd-7.8.14.tgz
    version: 7.8.14
  - annotations:
      artifacthub.io/changes: |
        - kind: security
          description: updated redis dependency to 7.0.13-alpine to fix CVE-2022-48174
      artifacthub.io/signKey: |
        fingerprint: 2B8F22F57260EFA67BE1C5824B11F800CD9D2252
        url: https://argoproj.github.io/argo-helm/pgp_keys.asc
    apiVersion: v2
    appVersion: v2.8.4
    created: "2025-04-17T14:50:30.681927608+08:00"
    dependencies:
    - condition: redis-ha.enabled
      name: redis-ha
      repository: https://dandydeveloper.github.io/charts/
      version: 4.23.0
    description: A Helm chart for Argo CD, a declarative, GitOps continuous delivery
      tool for Kubernetes.
    digest: ab20e5f4e1d0deecb83d9f654e07fd6666bce4a7f328717a80220a81e8db6640
    home: https://github.com/argoproj/argo-helm
    icon: https://argo-cd.readthedocs.io/en/stable/assets/logo.png
    keywords:
    - argoproj
    - argocd
    - gitops
    kubeVersion: '>=1.23.0-0'
    maintainers:
    - name: argoproj
      url: https://argoproj.github.io/
    name: argo-cd
    sources:
    - https://github.com/argoproj/argo-helm/tree/main/charts/argo-cd
    - https://github.com/argoproj/argo-cd
    urls:
    - argo/argo-cd-5.46.7.tgz
    version: 5.46.7
  common:
  - annotations:
      category: Infrastructure
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 2.22.0
    created: "2025-04-17T14:50:30.772268557+08:00"
    description: A Library Helm Chart for grouping common logic between bitnami charts.
      This chart is not deployable by itself.
    digest: f08ada920444add76d87a23c588089bfa1a59dd9cf516abe47bbc8aa0da9aee4
    home: https://bitnami.com
    icon: https://bitnami.com/downloads/logos/bitnami-mark.png
    keywords:
    - common
    - helper
    - template
    - function
    - bitnami
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: common
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/common
    type: library
    urls:
    - k8s/common-2.22.0.tgz
    version: 2.22.0
  ingress-nginx:
  - annotations:
      artifacthub.io/changes: |
        - Update Ingress-Nginx version controller-v1.11.3
      artifacthub.io/prerelease: "false"
    apiVersion: v2
    appVersion: 1.11.3
    created: "2025-04-17T14:50:30.804170299+08:00"
    description: Ingress controller for Kubernetes using NGINX as a reverse proxy
      and load balancer
    digest: a9f371489a6c18042508c0b5c2ea669deaad7ccc08f37efc4522e336edda1c20
    home: https://github.com/kubernetes/ingress-nginx
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c5/Nginx_logo.svg/500px-Nginx_logo.svg.png
    keywords:
    - ingress
    - nginx
    kubeVersion: '>=1.21.0-0'
    maintainers:
    - name: cpanato
    - name: Gacko
    - name: puerco
    - name: rikatz
    - name: strongjz
    - name: tao12345666333
    name: ingress-nginx
    sources:
    - https://github.com/kubernetes/ingress-nginx
    urls:
    - k8s/ingress-nginx-4.11.3.tgz
    version: 4.11.3
  mariadb:
  - annotations:
      category: Database
      images: |
        - name: mariadb
          image: docker.io/bitnami/mariadb:11.4.3-debian-12-r0
        - name: mysqld-exporter
          image: docker.io/bitnami/mysqld-exporter:0.15.1-debian-12-r30
        - name: os-shell
          image: docker.io/bitnami/os-shell:12-debian-12-r27
      licenses: Apache-2.0
    apiVersion: v2
    appVersion: 11.4.3
    created: "2025-04-17T14:50:30.811426121+08:00"
    dependencies:
    - name: common
      repository: oci://registry-1.docker.io/bitnamicharts
      tags:
      - bitnami-common
      version: 2.x.x
    description: MariaDB is an open source, community-developed SQL database server
      that is widely in use around the world due to its enterprise features, flexibility,
      and collaboration with leading tech firms.
    digest: ed780b0bcd454aabbbbaed5974e735b918757e649112175bd63c9ee015217a90
    home: https://bitnami.com
    icon: https://bitnami.com/assets/stacks/mariadb/img/mariadb-stack-220x234.png
    keywords:
    - mariadb
    - mysql
    - database
    - sql
    - prometheus
    maintainers:
    - name: Broadcom, Inc. All Rights Reserved.
      url: https://github.com/bitnami/charts
    name: mariadb
    sources:
    - https://github.com/bitnami/charts/tree/main/bitnami/mariadb
    urls:
    - k8s/mariadb-19.0.6.tgz
    version: 19.0.6
  ska-src-dm-da-service-gatekeeper:
  - apiVersion: v2
    appVersion: 0.1.8
    created: "2025-04-17T14:50:30.770765761+08:00"
    dependencies:
    - name: ingress-nginx
      repository: https://aaronyang0628.github.io/helm-chart-mirror/charts
      version: 4.11.3
    description: A chart for the deployment of the SRCNet Service Gatekeeper (a modified
      version of ingress-nginx).
    digest: 8726a3e991a39b0efc60c0976fcaec007c6faef05e72be94ebc9e47c5e3c1dd0
    home: https://gitlab.com/ska-telescope/src/src-dm/ska-src-dm-da-service-gatekeeper
    name: ska-src-dm-da-service-gatekeeper
    sources:
    - https://gitlab.com/ska-telescope/src/src-dm/ska-src-dm-da-service-gatekeeper
    type: application
    urls:
    - cnsrc/ska-src-dm-da-service-gatekeeper-0.2.0.tgz
    version: 0.2.0
  slurm:
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 24.05.3
    created: "2025-04-17T14:50:30.932866937+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 2.22.0
    - condition: mariadb.enabled
      name: mariadb
      repository: https://charts.bitnami.com/bitnami
      version: 19.0.6
    description: A Helm chart for Slurm Cluster
    digest: 549c5c580e78b0846ca62c34f6c2245b2c3fd3ecab4fbcc3cfb4cab68333bb49
    home: https://github.com/AaronYang0628/slurm-on-k8s/tree/main/chart
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Slurm_logo.svg/262px-Slurm_logo.svg.png
    keywords:
    - slurm
    - hpc
    - k8s
    maintainers:
    - name: Aaron Yang
      url: https://github.com/AaronYang0628
    name: slurm
    sources:
    - https://github.com/AaronYang0628/slurm-on-k8s/tree/main/chart
    urls:
    - slurm/slurm-1.0.6.tgz
    version: 1.0.6
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 24.05.3
    created: "2025-04-17T14:50:30.884798981+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 2.22.0
    - condition: mariadb.enabled
      name: mariadb
      repository: https://charts.bitnami.com/bitnami
      version: 19.0.6
    description: A Helm chart for Slurm Cluster
    digest: 1efac6f2a0cdfa4a27026cfe68434eba4b93bbbe17304b6672149c466e743e2d
    home: https://github.com/AaronYang0628/slurm-on-k8s/tree/main/chart
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Slurm_logo.svg/262px-Slurm_logo.svg.png
    keywords:
    - slurm
    - hpc
    - k8s
    maintainers:
    - name: Aaron Yang
      url: https://github.com/AaronYang0628
    name: slurm
    sources:
    - https://github.com/AaronYang0628/slurm-on-k8s/tree/main/chart
    urls:
    - slurm/slurm-1.0.5.tgz
    version: 1.0.5
  - annotations:
      category: Infrastructure
    apiVersion: v2
    appVersion: 24.05.3
    created: "2025-04-17T14:50:30.87062448+08:00"
    dependencies:
    - name: common
      repository: https://charts.bitnami.com/bitnami
      version: 2.22.0
    - condition: mariadb.enabled
      name: mariadb
      repository: https://charts.bitnami.com/bitnami
      version: 19.0.6
    description: A Helm chart for Slurm Cluster
    digest: efdc4db3b1cce46abf1a84677d75397633cd4b43a02a76196b50500ebd795593
    home: https://github.com/AaronYang0628/slurm-on-k8s/tree/main/chart
    icon: https://upload.wikimedia.org/wikipedia/commons/thumb/3/3a/Slurm_logo.svg/262px-Slurm_logo.svg.png
    keywords:
    - slurm
    - hpc
    - k8s
    maintainers:
    - name: Aaron Yang
      url: https://github.com/AaronYang0628
    name: slurm
    sources:
    - https://github.com/AaronYang0628/slurm-on-k8s/tree/main/chart
    urls:
    - slurm/slurm-1.0.4.tgz
    version: 1.0.4
generated: "2025-04-17T14:50:30.606784536+08:00"
