name: update-mirror
on:
  workflow_dispatch: 
jobs:
  publish-github-pages:
    permissions:
      pages: write
      id-token: write
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: update-mirror
        uses: addnab/docker-run-action@v3
        with:
          registry: gcr.io
          image: ghcr.io/ben-wangz/blog-helm-mirror:main
          options: -v ${{ github.workspace }}:/code -e CHART_YAML_FILE=/code/charts.yaml -e DESTINATION=/code/charts
          shell: bash
          run: /app/mirror.sh
      - name: upload github pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}
          retention-days: 1
      - name: deploy to gitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
