name: update-mirror
on:
  workflow_dispatch: 
jobs:
  upload-artifact:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.pull_request.head.repo.full_name }}
          ref: ${{ github.event.pull_request.head.ref }}
      - name: update-mirror
        uses: addnab/docker-run-action@v3
        with:
          registry: gcr.io
          image: ghcr.io/ben-wangz/blog-helm-mirror:main
          options: -v ${{ github.workspace }}:/code -e CHART_YAML_FILE=/code/charts.yaml -e DESTINATION=/code/charts
          shell: bash
          run: /app/mirror.sh
      - name: archive artifact
        env:
          INPUT_PATH: ${{ github.workspace }}
        shell: sh
        run: |
          tar \
            --dereference --hard-dereference \
            --directory "$INPUT_PATH" \
            -cvf "$RUNNER_TEMP/artifact.tar" \
            --exclude=.git \
            --exclude=.github \
            .
      - name: upload artifact
        id: upload-artifact
        uses: actions/upload-artifact@v4
        with:
          name: helm-chart-mirror-github-pages
          path: ${{ runner.temp }}/artifact.tar
          retention-days: 1
          overwrite: true
          if-no-files-found: error
  deploy-artifact:
    needs: upload-artifact
    permissions:
      pages: write
      id-token: write
    environment:
      name: helm-chart-mirror-github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: deploy to gitHub pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          artifact_name: helm-chart-mirror-github-pages
        
          
